pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/shambbaz/Slots-Game.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest tests/'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t slots-game .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh 'docker run -it slots-game'
            }
        }
    }
}
